version: "3.9"

services:
  build:
    image: klakegg/hugo:0.101.0
    volumes:
      - "./myblog:/src"
  server:
    image: klakegg/hugo:0.101.0
    command: server
    volumes:
      - "./myblog:/src"
    ports:
      - "1313:1313"

